### ISSUE TITLE
Provide a way to select network interface

### ISSUE THREAD

**Issue by it9exm** [go-debos/fakemachine#122]
Hello,

It looks like fakemachine is always using the 1st available network interface. In my case it is the ethernet interface enp3s0, which is down as I am using wifi (wlp2s0). I can't find any way to change between them. Do you confirm there's no such feature atm or I am missing something?

Please note that because of that I had troubles to use [these tools where fakemachine is suggested](https://salsa.debian.org/raspi-team/image-specs/-/issues/64).

Thank you

**Comment by obbardc** [comment]
Fakemachine should work with any network interface on your host. Possibly you are seeing https://github.com/go-debos/fakemachine/issues/123 ?

**Comment by it9exm** [comment]
Sure, my assumption was wrong, it is #123 
I'm closing this.
