### ISSUE TITLE
Assumes the host machine is always x86_64

### ISSUE THREAD

**Issue by smcv** [go-debos/fakemachine#18]
Even if fakemachine is built for a non-x86_64 architecture, it hard-codes `qemu-system-x86_64` as the way to run the fake machine.

**Comment by smcv** [comment]
It also hard-codes the assumption that the linker is /lib64/ld-linux-x86-64.so.2 and the standard C library is /lib/x86_64-linux-gnu/libc.so.6, neither of which is going to work on non-x86.

https://sourceware.org/glibc/wiki/ABIList and https://gitlab.collabora.com/vivek/libcapsule/blob/master/utils/capture-libs.c have a reasonably complete list of runtime linker paths, if that's any help?

**Comment by obbardc** [comment]
fakemachine builds properly for arm64 now; we may add further architectures later if there is a need.
