### ISSUE TITLE
"payload" command containing shell metacharacters doesn't work correctly

### ISSUE THREAD

**Issue by smcv** [go-debos/fakemachine#32]
Steps to reproduce: for example

```
$ fakemachine -- python -c 'import sys;print(sys.argv)' "foo bar"
```

Expected result: same as `python -c 'import sys;print(sys.argv)' "foo bar"`, i.e. `['-c', 'foo bar']`, possibly surrounded by some extra noise

Actual result:

```
Running python -c import sys;print(sys.argv) foo bar
/wrapper: 4: /wrapper: Syntax error: word unexpected (expecting ")")
Powering off.
```

---

My suggested solution (I don't know enough Go to implement this myself any time soon) would be to have the same command-line syntax as `vectis run` in <https://salsa.debian.org/smcv/vectis>:

```
fakemachine -- argv0 argv1 --argv2 --argv3
(and optionally)
fakemachine -c "your shell one-liner here"
```

* Use some Go library analogous to Python `shlex.quote` to escape the shell command as written into `/wrapper`, or implement a similar thing with string manipulation functions directly
* Optionally add a `-c` argument that returns to the current behaviour, so you can use `fakemachine -c "if foo; then bar; fi"` if you already have a shell one-liner that you want to use (without having to use `-- sh -c` and get a pointless extra layer of shell quoting/parsing)

**Comment by obbardc** [comment]
I've tried to run e.g `fakemachine "echo test1 && echo test2"`, which worked before 639d6af6ba9cd665476e3ae936a0a257d229f505, now results in:

```
$ fakemachine "echo test1 && echo test2"
Running 'echo test1 && echo test2' using kvm backend
/wrapper: 14: echo test1 && echo test2: not found
```

**Comment by smcv** [comment]
That probably means that this issue has been fixed, at the cost of breaking use-cases that weren't necessarily meant to work but accidentally worked anyway.

(Something like `fakemachine -- sh -c 'echo test1 && echo test2'` would be the way to run arbitrary shell commands after fixing this issue.)

**Comment by obbardc** [comment]
Right. I guess we can consider this closed then!
