### ISSUE TITLE
Add --environ option to the fakemachine command

### ISSUE THREAD

**Issue by elboulangero** [go-debos/fakemachine#40]
It would be nice if fakemachine would support `-e, --environ` option on the command-line to pass environment variables. Also, automatic support for `http_proxy` and friends would be nice.

So basically, what's be done in https://github.com/go-debos/debos/commit/d5de0f1.

fakemachine already supports passing environment variables to the VM since 5a2e8e74a, however it's not exposed to the commandl-line command.

Use-case: I used `fakemachine mkosi ...` to run mkosi from within a container, and I wish I could forward `http_proxy` to mkosi, the same way it's done with debos, to speed-up package downloads.

**Comment by obbardc** [comment]
all merged!
