### ISSUE TITLE
UML should only be able to be ran on amd64

### ISSUE THREAD

**Issue by obbardc** [go-debos/fakemachine#59]
Currently we can attempt to run the UML backend on other archs, but it obviously fails.

**Comment by sjoerdsimons** [comment]
For refence debos only supports running on amd64 anyway; #30 had a attempt to fix that, which might be more interesting again now since both AWS and Azure (in preview) are starting to have 64 bit arm runners, which would allow potentially building arm images without cpu emulation

**Comment by sjoerdsimons** [comment]
See also #18

**Comment by obbardc** [comment]
Fixed with #157
