### ISSUE TITLE
Doesn't work with zstd compressed kernel modules

### ISSUE THREAD

**Issue by 14mRh4X0r** [go-debos/fakemachine#69]
Linux 5.13+ supports building zstd compressed kernel modules, but support for loading them with Busybox [is still being worked on](https://www.mail-archive.com/busybox@busybox.net/msg27734.html). In the meantime, at least Arch Linux ships their kernel with zstd compressed modules.

I'm not entirely sure whether this is something that even should be fixed -- for example, you could argue that people should be using a busybox version that supports their setup -- or, if it should be, in what way. The only way I can think of is to include `kmod` with its dependencies, which would be a bit messy, but doable.

**Comment by evelikov** [comment]
I have a branch which fixes that actually. Let me rebase, test and submit a PR

**Comment by sjoerdsimons** [comment]
Fixes by #72
